# action.yaml
name: 'Clean Workspace'
description: 'Clean Workspace'
inputs:
  os:
    description: 'The command to run'
    required: true

runs:
  using: 'composite'
  steps:
    # - name: Run cleanup script on Windows
    #   shell: pwsh
    #   run: printenv

    # - name: Load environment variables
    #   if: ${{ inputs.os == 'Windows' }}
    #   run: "${{ env.PYTHON_ALIAS }} ${{ env.SOURCECODE_FOLDER }}/pipelines/scripts/env_prepare.py --platform github"
    #   shell: pwsh

    - name: Task for Windows
      if: ${{ inputs.os == 'Windows' }}
      shell: pwsh
      run: |
        Write-Host "Windows: ${{ runner.os }}" 
        Write-Host "Windows: ${{ inputs.os }}"

    - name: Task for Linux/MacOS
      if: ${{ inputs.os == 'Linux' }}
      shell: bash
      run: |
        Write-Host "Linux: ${{ runner.os }}" 
        Write-Host "Linux input: ${{ inputs.os }}"

    # - name: Task for Windows
    #   shell: pwsh
    #   run: |
    #     if ($env:RUNNER_OS -eq 'Windows') {
    #       Write-Host "Running on Windows"
    #       Write-Host "Example input: $env:RUNNER_OS"
    #     }

    # - name: Run cleanup script on Windows
    #   run: |
    #     echo "::group::Start of Linux/MacOS Task"  
    #     echo 'Windows shell: ${{ env.RUNNER_OS }}'
    #     echo "Running on Linux/MacOS"
    #     echo "Example input: ${{ inputs.example_input }}"
    #     echo "::endgroup::"
    #     echo "::group::Start of 2222 Linux/MacOS Task"  
    #     echo 'Windows shell: ${{ env.RUNNER_OS }}'
    #     echo "Running on Linux/MacOS"
    #     echo "Example input: ${{ inputs.example_input }}"
    #     echo "::endgroup::"
        
    #   shell: pwsh

    # - name: Run cleanup script on Linux
    #   run: "echo 'Linux shell: $os'"
    #   shell: bash