# action.yaml
name: 'Job Upload Artifacts'
description: 'Job Upload Artifacts'
inputs:
  job-name:
    description: 'Job name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Upload Job Artifacts
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: "${{ env.PYTHON_ALIAS }} ${{ env.PY_SCRIPTS_LOCATION }}/job_delta_upload.py --jobname \"${{ inputs.job-name }}\" --errordetected false"

    - name: Collect Pipeline Artifacts
      if: ${{ (runner.os == 'Windows') && (env.IS_COLLECTING_ARTIFACTS == 'true') }}
      shell: pwsh
      run: "${{ env.PYTHON_ALIAS }} ${{ env.PY_SCRIPTS_LOCATION }}/job_collect_artifacts.py --jobname \"${{ inputs.job-name }}\" --skip_compression"

    - name: Upload Job Artifacts
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: "${{ env.PYTHON_ALIAS }} ${{ env.PY_SCRIPTS_LOCATION }}/job_delta_upload.py --jobname \"${{ inputs.job-name }}\" --errordetected false"

    - name: Collect Pipeline Artifacts
      if: ${{ (runner.os != 'Windows') && (env.IS_COLLECTING_ARTIFACTS == 'true') }}
      shell: bash
      run: "${{ env.PYTHON_ALIAS }} ${{ env.PY_SCRIPTS_LOCATION }}/job_collect_artifacts.py --jobname \"${{ inputs.job-name }}\" --skip_compression"

    - name: Upload Pipeline Artifacts
      if: ${{ env.IS_COLLECTING_ARTIFACTS == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACTS_FILE_NAME_STEM }}
        path: ${{ env.DONWLOADS_FOLDER }}