# action.yaml
name: 'Job Execute'
description: 'Job Execute'
inputs:
  job-name:
    description: 'Job name'
    required: true
  use-matlab-plugin:
    description: 'Use matlab plugin'
    required: true
  enable-dryrun:
    description: 'Enable Dryrun'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Job Dryrun Execute for Windows
      if: ${{ (runner.os == 'Windows') && (inputs.enable-dryrun == 'true') }}
      shell: pwsh
      run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_dryrun.py --jobname \"${{ inputs.job-name }}\""

    - name: Job Dryrun Execute for Linux/MacOS
      if: ${{ (runner.os != 'Windows') && (inputs.enable-dryrun == 'true') }}
      shell: bash
      run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_dryrun.py --jobname \"${{ inputs.job-name }}\""

    - name: Job Execute for Windows
      if: ${{ (runner.os == 'Windows') && (inputs.enable-dryrun != 'true') && (inputs.use-matlab-plugin != 'true') }}
      shell: pwsh
      run: ./shell_commands.bat

    - name: Job Execute for Linux/MacOS
      if: ${{ (runner.os != 'Windows') && (inputs.enable-dryrun != 'true') && (inputs.use-matlab-plugin != 'true') }}
      shell: bash
      run: ./shell_commands.sh

    - name: Job Execute using MATLAB plugin
      if: ${{ (inputs.enable-dryrun != 'true') && (inputs.use-matlab-plugin == 'true') }}
      uses: matlab-actions/run-command@v2
      with:
        command: "matlab_job_commands"