name: Balanced DAG Workflow
on: # You must define at least one trigger for each workflow.
  workflow_dispatch:  # Set manual triggers as an optional trigger.
  pull_request:       # Set pull_request as an automatic trigger. By default, a pull_request runs when a pull_request event's activity type is opened, synchronize, or reopened
    # opened: This triggers the workflow when a pull request is initially opened.
    # synchronize: This triggers the workflow when new commits are pushed to a pull request branch. This includes any time the pull request's head branch is updated with new commits.
    # reopened: This triggers the workflow when a previously closed pull request is reopened
    types: [opened, synchronize, reopened]

jobs:
  start:
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "start"

  #######################################################################
  #                 AHRS_Voter
  #######################################################################
  AHRS_Voter_L1A:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "AHRS_Voter_L1A"

  AHRS_Voter_L1B:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "AHRS_Voter_L1B"

  AHRS_Voter_L2B:
    needs: ["AHRS_Voter_L1B", "Actuator_Control_L1B", "InnerLoop_Control_L1B"]
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "AHRS_Voter_L2B"

  #######################################################################
  #                 Actuator_Control
  #######################################################################
  Actuator_Control_L1A:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "Actuator_Control_L1A"

  Actuator_Control_L1B:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "Actuator_Control_L1B"

  Actuator_Control_L2B:
    needs: Actuator_Control_L1B
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "Actuator_Control_L2B"

  #######################################################################
  #                 InnerLoop_Control
  #######################################################################
  InnerLoop_Control_L1A:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "InnerLoop_Control_L1A"

  InnerLoop_Control_L1B:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "InnerLoop_Control_L1B"

  InnerLoop_Control_L2B:
    needs: ["AHRS_Voter_L1B", "Actuator_Control_L1B", "InnerLoop_Control_L1B"]
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "InnerLoop_Control_L2B"


  #######################################################################
  #                 OuterLoop_Control
  #######################################################################
  OuterLoop_Control_L1A:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "OuterLoop_Control_L1A"

  #######################################################################
  #                 Flight_Control & OuterLoop_Control
  #######################################################################
  Flight_Control_L1A:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "Flight_Control_L1A"

  Flight_Control_L2A:
    needs: Flight_Control_L1A
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "Flight_Control_L2A"

  Top_Model_Tasks:
    needs: [AHRS_Voter_L1A, Actuator_Control_L1A, InnerLoop_Control_L1A, OuterLoop_Control_L1A]
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "Top_Model_Tasks"

  #######################################################################
  #                 end
  #######################################################################
  end:
    needs:
      [
        Top_Model_Tasks,
        AHRS_Voter_L2B,
        Actuator_Control_L2B,
        InnerLoop_Control_L2B,
        Flight_Control_L2A
      ]
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: "end"
