name: Single Job Workflow
on:                                           # You must define at least one trigger for each workflow.
  workflow_dispatch:                          # Set manual triggers as the default trigger, while it is not intended to be activated manually.

jobs:
  start:
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: start

  AHRS_Voter:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: AHRS_Voter

  Actuator_Control:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: Actuator_Control

  Flight_Control:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: Flight_Control

  InnerLoop_Control:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: InnerLoop_Control

  OuterLoop_Control:
    needs: start
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: OuterLoop_Control

  end:
    needs: [AHRS_Voter, Actuator_Control, Flight_Control, InnerLoop_Control, OuterLoop_Control]
    if: (vars.CONTINUE_ON_ERROR == 'true' || !failure()) && !cancelled()
    uses: ./.github/workflows/generic-job.yml
    with:
      job-name: end