name: Container Job
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      
jobs:
  Container-Job:
    name: Container Job
    runs-on: ${{ vars.RUNNER_LABEL }}
    container:
      image: ${{ vars.IMAGE_TAG }}  
      volumes:
        - /home/ahmedh/project/derived/licenses:/opt/matlab/R2024b/licenses
        - /home/ahmedh/artifactory:/home/ahmedh/artifactory
    env:
      WORKSPACE_PATH_KEY: GITHUB_WORKSPACE
      SOURCECODE_FOLDER: ${{ vars.SOURCECODE_FOLDER || 'scm' }}
      PYTHON_ALIAS: ${{ vars.PYTHON_ALIAS || 'python' }}
      HOME: /home/matlab

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ env.SOURCECODE_FOLDER }}

      - name: Load environment variables
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SOURCECODE_FOLDER }}/pipelines/scripts/env_prepare.py --platform github"

      - name: Clean Workspace
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_clean.py"

      - name: Job Preparation
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_prepare.py --jobname \"${{ inputs.job-name }}\""

      - name: Download Artifacts
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_download.py --jobname \"${{ inputs.job-name }}\""

      - name: Execute Job tasks
        uses: ./scm/.github/actions/job-execute
        with:
          job-name: ${{ inputs.job-name }}
          enable-dryrun: ${{ env.ENABLE_CI_DRYRUN }}

      - name: Upload Artifacts
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_delta_upload.py --jobname \"${{ inputs.job-name }}\" --errordetected false"