name: Reusable Workflow - Generic Job
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      
jobs:
  Generic-Job:
    name: Generic Job
    runs-on: ${{ vars.RUNNER_LABEL }}
    env:
      PYTHON_ALIAS: ${{ vars.PYTHON_ALIAS || 'python' }}
      SUBMODULES_MODE: ${{ vars.SUBMODULES_MODE || 'false' }}
      WORKSPACE_PATH_KEY: GITHUB_WORKSPACE
      SOURCECODE_FOLDER: ${{ vars.SOURCECODE_FOLDER || 'scm' }}
      SCRIPTS_LOCATION: "${{ vars.SOURCECODE_FOLDER || 'scm' }}/pipelines/scripts"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.SOURCECODE_FOLDER }}
          submodules: ${{ env.SUBMODULES_MODE }}

      - name: Download ir_dag
        uses: actions/download-artifact@v4
        with:
            name: ir_dag

      - name: Load environment variables
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/env_prepare.py --platform github"

      - name: Clean Workspace
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_clean.py"

      - name: Job Preparation
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_prepare.py --jobname \"${{ inputs.job-name }}\""

      - name: Download Artifacts
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_download.py --jobname \"${{ inputs.job-name }}\""

      - name: Execute Job tasks
        uses: ./scm/.github/actions/job-execute
        with:
          job-name: ${{ inputs.job-name }}
          use-matlab-plugin: ${{ env.USE_MATLAB_PLUGIN }}
          enable-dryrun: ${{ env.ENABLE_CI_DRYRUN }}

      - name: Upload Artifacts
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_delta_upload.py --jobname \"${{ inputs.job-name }}\" --errordetected false"