# Copyright 2025 The MathWorks, Inc.
name: Reusable Workflow - Generic Job
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      
jobs:
  Generic-Job:
    name: Generic Job
    runs-on: ${{ vars.RUNNER_LABEL }}
    env:
      PYTHON_ALIAS: ${{ vars.PYTHON_ALIAS || 'python' }}
      SUBMODULES_MODE: ${{ vars.SUBMODULES_MODE || 'false' }}
      WORKSPACE_PATH_KEY: GITHUB_WORKSPACE
      SCM_FOLDER: ${{ vars.SCM_FOLDER || 'scm' }}
      SUPPORT_PACKAGE_ROOT: ${{ vars.SUPPORT_PACKAGE_ROOT || 'scm' }}
      PY_SCRIPTS_LOCATION: "${{ vars.SUPPORT_PACKAGE_ROOT || 'scm' }}/toolbox/padv/pipeline_generator/ci/py"
      NETWORK_STORAGE_PATH: ${{ vars.NETWORK_STORAGE_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ env.SCM_FOLDER }}
          submodules: ${{ env.SUBMODULES_MODE }}

      - name: Download ir_dag
        uses: actions/download-artifact@v4
        with:
            name: ir_dag
            path: ${{ env.SCM_FOLDER }}

      - name: Load environment variables
        run: "${{ env.PYTHON_ALIAS }} ${{ env.PY_SCRIPTS_LOCATION }}/env_prepare.py --platform github"

      - name: Clean Workspace
        run: "${{ env.PYTHON_ALIAS }} ${{ env.PY_SCRIPTS_LOCATION }}/job_clean.py"

      - name: Job Preparation
        run: "${{ env.PYTHON_ALIAS }} ${{ env.PY_SCRIPTS_LOCATION }}/job_prepare.py --jobname \"${{ inputs.job-name }}\" --platform github"

      - name: Download Artifacts
        run: "${{ env.PYTHON_ALIAS }} ${{ env.PY_SCRIPTS_LOCATION }}/job_download.py --jobname \"${{ inputs.job-name }}\""

      - name: Execute Job tasks
        uses: ./scm/.github/actions/job-execute
        with:
          job-name: ${{ inputs.job-name }}
          use-matlab-plugin: ${{ env.USE_MATLAB_PLUGIN }}
          enable-dryrun: ${{ env.ENABLE_CI_DRYRUN }}

      - name: Upload Job Artifacts
        uses: ./scm/.github/actions/job-upload-artifacts
        with:
          job-name: ${{ inputs.job-name }}