name: Generic Job
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      job-name:
        required: true
        type: string
      agent-label:
        required: true
        type: string
      
jobs:
  Generic-Linux-Job:
    name: Generic Job
    runs-on: ${{ inputs.agent-label }}
    env:
      WORKSPACE_PATH_KEY: GITHUB_WORKSPACE
      SOURCECODE_FOLDER: scm
      PYTHON_ALIAS: python

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ env.SOURCECODE_FOLDER }}
      
      - run: python --version

      - name: Load environment variables
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SOURCECODE_FOLDER }}/pipelines/scripts/env_prepare.py --platform github"

      - name: Clean Workspace
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_clean.py"

      - name: Job Preparation
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_prepare.py --jobname \"${{ inputs.job-name }}\""

      - name: Download Artifacts
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_download.py --jobname \"${{ inputs.job-name }}\""

      - name: Tasks Execution
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_dryrun.py --jobname \"${{ inputs.job-name }}\""

      - name: Execute Job tasks
        uses: ./.github/actions/job-execute
        with:
          job-name: ${{ inputs.job-name }}
          enable-dryrun: ${{ env.ENABLE_CI_DRYRUN }}

      - name: Upload Artifacts
        run: "${{ env.PYTHON_ALIAS }} ${{ env.SCRIPTS_LOCATION }}/job_delta_upload.py --jobname \"${{ inputs.job-name }}\" --errordetected false"