# Copyright 2025 The MathWorks, Inc.
name: MATLAB Workflow2
on: # You must define at least one trigger for each workflow.
  workflow_dispatch:  # Set manual triggers as an optional trigger.
  pull_request:       # Set pull_request as an automatic trigger. 
                      # By default, a pull_request runs when a pull_request 
                      # event's activity type is opened, synchronize, or reopened
    # opened: This triggers the workflow when a pull request is initially opened.
    # synchronize: This triggers the workflow when new commits are pushed to a pull request branch. This includes any time the pull request's head branch is updated with new commits.
    # reopened: This triggers the workflow when a previously closed pull request is reopened
    types: [opened, synchronize, reopened]
    
jobs:
  Run_MATLAB_Tasks:
    name: Run_MATLAB_Tasks
    runs-on: ${{ vars.RUNNER_LABEL }}

    steps:
      - name: Add MATLAB to PATH
        # run: echo "D:/sb/Bslcicd_0209/matlab/bin" >> $GITHUB_PATH
        run: echo "D:/sb/Bslcicd_0209/matlab/bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
        
      - name: Run MATLAB Tasks
        uses: matlab-actions/run-command@v2
        with:
          command: "disp(pwd);runMatlabTasks;"